version: '3.8'

services:
  go-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: host=postgres port=5432 user=postgres password=postgres dbname=ktaxes sslmode=disable
      ADMIN_USERNAME: adminTax
      ADMIN_PASSWORD: admin!
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql